wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 64
hidden_layers:
  value: 3
lr:
  value: 0.001
optimiser:
  value: sgd
weight_init:
  value: xavier
