wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 5
lr:
  value: 0.0001
optimiser:
  value: adam
weight_init:
  value: random
