wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 3
lr:
  value: 0.001
optimiser:
  value: adam
weight_init:
  value: random
