wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 4
lr:
  value: 0.001
optimiser:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: xavier
