wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
hidden_layers:
  value: 3
lr:
  value: 0.001
optimiser:
  value: sgd
weight_decay:
  value: 0.5
weight_init:
  value: xavier
