wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.8.3
      5: 0.10.22
      8:
      - 1
      - 5
activation:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
hidden_layer_size:
  desc: null
  value: 64
hidden_layers:
  desc: null
  value: 3
lr:
  desc: null
  value: 0.001
optimiser:
  desc: null
  value: sgd
test_accuracy:
  desc: null
  value: 0.0999
test_loss:
  desc: null
  value: 1.996100069138443
train_accuracy:
  desc: null
  value: 0.09988888888888889
train_loss:
  desc: null
  value: 1.9960672657549017
val_accuracy:
  desc: null
  value: 0.0985
val_loss:
  desc: null
  value: 1.996200718795203
weight_init:
  desc: null
  value: xavier
